import { requireAdmin } from '@/utils/auth';
import Link from 'next/link';
import SignOutButton from '@/components/SignOutButton';
import { ThemeToggle } from '@/components/ThemeToggle';
import { Settings, Layers, Workflow, TestTube2, MessageSquare } from 'lucide-react';

export default async function Dashboard() {
  const user = await requireAdmin();

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8 transition-colors">
      <div className="max-w-7xl mx-auto">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-12 gap-4">
          <div>
            <h1 className="text-4xl font-extrabold text-gray-900 dark:text-white sm:text-5xl sm:tracking-tight flex items-center gap-3">
              <Workflow className="h-10 w-10 text-blue-600" />
              Prompt Chain Tool
            </h1>
            <p className="mt-2 text-xl text-gray-500 dark:text-gray-400">
              Manage Humor Flavors and Generation Pipelines
            </p>
          </div>
          <div className="flex items-center gap-4">
            <ThemeToggle />
            <div className="text-sm text-gray-500 dark:text-gray-400 font-medium">
              {user.email}
            </div>
            <SignOutButton />
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {/* Flavor Management */}
          <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-md border border-gray-200 dark:border-gray-700 hover:shadow-lg transition-all">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-3 bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400 rounded-lg">
                <Layers className="h-6 w-6" />
              </div>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white">Humor Flavors</h2>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-6 text-sm">
              Define the core styles of humor (e.g., "Dark", "Gen Z"). These act as the parent containers for prompt steps.
            </p>
            <Link
              href="/flavors"
              className="inline-flex items-center justify-center w-full bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-md transition-colors font-medium"
            >
              Manage Flavors
            </Link>
          </div>

          {/* Testing Tool */}
          <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-md border border-gray-200 dark:border-gray-700 hover:shadow-lg transition-all border-t-4 border-t-blue-500">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-3 bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 rounded-lg">
                <TestTube2 className="h-6 w-6" />
              </div>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white">Pipeline Tester</h2>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-6 text-sm">
              Test your prompt chains by running images through specific Humor Flavors using the live generation API.
            </p>
            <Link
              href="/test-pipeline"
              className="inline-flex items-center justify-center w-full bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md transition-colors font-medium"
            >
              Open Tester
            </Link>
          </div>

          {/* Results Viewer */}
          <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-md border border-gray-200 dark:border-gray-700 hover:shadow-lg transition-all">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-3 bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400 rounded-lg">
                <MessageSquare className="h-6 w-6" />
              </div>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white">Captions Viewer</h2>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-6 text-sm">
              Browse and review all captions generated by the system, filterable by specific Humor Flavors.
            </p>
            <Link
              href="/captions"
              className="inline-flex items-center justify-center w-full bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-md transition-colors font-medium"
            >
              View Captions
            </Link>
          </div>
        </div>

      </div>
    </div>
  );
}
